provider: azure
lint: false
major-version: 5
parallel: 2
timeout: 90
providerVersion: github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_ENVIRONMENT: "public"
  ARM_LOCATION: "westus2"
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  PULUMI_MISSING_DOCS_ERROR: true
upstream-provider-org: pulumi
upstream-provider-repo: terraform-provider-azurerm
makeTemplate: bridged
plugins:
  - name: random
    version: "4.1.1"
  - name: azuread
    version: "4.0.0"
