provider: github
major-version: 4
env:
  GH_ORGANIZATION: ${{ secrets.GH_ORGANIZATION }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TESTING_TOKEN: ${{ secrets.GH_TESTING_TOKEN }}
upstream-provider-org: pulumi
makeTemplate: bridged
