self-hosted-runner:
  labels:
    - pulumi-ubuntu-8core

# Most of these ignores are in place because our esc-secrets action has dynamic
# outputs, and actionlint assumes all outputs are explicit.
paths:
  ".github/workflows/build_provider.yml":
    ignore:
      - 'property "azure_signing_client_id" is not defined in object type {}'
      - 'property "azure_signing_client_secret" is not defined in object type {}'
      - 'property "azure_signing_key_vault_uri" is not defined in object type {}'
      - 'property "azure_signing_tenant_id" is not defined in object type {}'

  ".github/workflows/build_sdk.yml":
    ignore:
      - 'property "pulumi_bot_token" is not defined in object type {}'

  ".github/workflows/command-dispatch.yml":
    ignore:
      - 'property "github_token" is not defined in object type {}'
      - 'property "pulumi_bot_token" is not defined in object type {}'

  ".github/workflows/community-moderation.yml":
    ignore:
      - 'property "github_token" is not defined in object type {}'

  ".github/workflows/main-post-build.yml":
    ignore:
      - 'property "aws_corp_s3_upload_access_key_id" is not defined in object type {}'
      - 'property "aws_corp_s3_upload_secret_access_key" is not defined in object type {}'
      - 'property "s3_coverage_bucket_name" is not defined in object type {}'

  ".github/workflows/master.yml":
    ignore:
      - 'property "release_ops_slack_channel" is not defined in object type {}'
      - 'property "release_bot_endpoint" is not defined in object type {}'
      - 'property "release_bot_key" is not defined in object type {}'
      - 'property "github_token" is not defined in object type {}'

  ".github/workflows/prerequisites.yml":
    ignore:
      - 'property "codecov_token" is not defined in object type {}'
      - 'property "github_token" is not defined in object type {}'

  ".github/workflows/publish.yml":
    ignore:
      - 'property "aws_access_key_id" is not defined in object type {}'
      - 'property "aws_secret_access_key" is not defined in object type {}'
      - 'property "aws_upload_role_arn" is not defined in object type {}'
      - 'property "github_token" is not defined in object type {}'
      - 'property "pulumi_bot_token" is not defined in object type {}'

  ".github/workflows/pull-request.yml":
    ignore:
      - 'property "github_token" is not defined in object type {}'

  ".github/workflows/release_command.yml":
    ignore:
      - 'property "release_ops_staging_slack_channel" is not defined in object type {}'
      - 'property "release_bot_endpoint" is not defined in object type {}'
      - 'property "release_bot_key" is not defined in object type {}'
      - 'property "github_token" is not defined in object type {}'

  ".github/workflows/run-acceptance-tests.yml":
    ignore:
      - 'property "codecov_token" is not defined in object type {}'
      - 'property "github_token" is not defined in object type {}'
      - 'property "pulumi_bot_token" is not defined in object type {}'

  ".github/workflows/build.yml":
    ignore:
      - 'property "aws_access_key_id" is not defined in object type {}'
      - 'property "aws_secret_access_key" is not defined in object type {}'
      - 'property "aws_upload_role_arn" is not defined in object type {}'
      - 'property "codecov_token" is not defined in object type {}'
      - 'property "github_token" is not defined in object type {}'
      - 'property "npm_token" is not defined in object type {}'
      - 'property "pulumi_bot_token" is not defined in object type {}'
      - 'property "release_bot_endpoint" is not defined in object type {}'
      - 'property "release_bot_key" is not defined in object type {}'
      - 'property "release_ops_slack_channel" is not defined in object type {}'

  ".github/workflows/prerelease.yml":
    ignore:
      - 'property "aws_access_key_id" is not defined in object type {}'
      - 'property "aws_secret_access_key" is not defined in object type {}'
      - 'property "aws_upload_role_arn" is not defined in object type {}'
      - 'property "codecov_token" is not defined in object type {}'
      - 'property "github_token" is not defined in object type {}'
      - 'property "npm_token" is not defined in object type {}'
      - 'property "pulumi_bot_token" is not defined in object type {}'

  ".github/workflows/release.yml":
    ignore:
      - 'property "aws_access_key_id" is not defined in object type {}'
      - 'property "aws_secret_access_key" is not defined in object type {}'
      - 'property "aws_upload_role_arn" is not defined in object type {}'
      - 'property "codecov_token" is not defined in object type {}'
      - 'property "github_token" is not defined in object type {}'
      - 'property "npm_token" is not defined in object type {}'
      - 'property "pulumi_bot_token" is not defined in object type {}'

  ".github/workflows/weekly-pulumi-update.yml":
    ignore:
      - 'property "pulumi_bot_token" is not defined in object type {}'

  ".github/workflows/nightly-sdk-generation.yml":
    ignore:
      - 'property "pulumi_bot_token" is not defined in object type {}'

  ".github/workflows/main.yml":
    ignore:
      - 'property "github_token" is not defined in object type {}'
      - 'property "release_bot_endpoint" is not defined in object type {}'
      - 'property "release_bot_key" is not defined in object type {}'
      - 'property "release_ops_slack_channel" is not defined in object type {}'
      - 'property "release_ops_staging_slack_channel" is not defined in object type {}'
