provider: external
major-version: 0
lint: false
providerDefaultBranch: main
makeTemplate: bridged
publishRegistry: false
env:
  EXTERNAL_TOKEN: ${{ secrets.EXTERNAL_TOKEN }}
team: ecosystem
javaGenVersion: "v0.9.7"
