name: "Verify Release"

on:
  workflow_dispatch:
    inputs:
      providerVersion:
        description: "The version of the provider to verify"
        required: true
        type: string
      enableMacRunner:
        description: "Enable the MacOS runner in addition to Linux and Windows. Defaults to 'false'."
        required: false
        type: boolean
      skipGoSdk:
        description: "Skip the Go SDK verification. Defaults to 'false'. Enable this when verifying a pre-release for which we don't publish the Go SDK (for PRs and the default branch)."
        required: false
        type: boolean
        default: false
      pythonVersion:
        description: "Optional python SDK version to verify. Defaults to inputs.providerVersion."
        type: string
        required: false
  workflow_call:
    inputs:
      providerVersion:
        description: "The version of the provider to verify"
        required: true
        type: string
      enableMacRunner:
        description: "Enable the macos-latest runner in addition to ubuntu-latest and windows-latest. Defaults to 'false'."
        required: false
        type: boolean
        default: false
      skipGoSdk:
        description: "Skip the Go SDK verification. Defaults to 'false'. This is used when we're not publishing a Go SDK on the default branch build."
        required: false
        type: boolean
        default: false
      pythonVersion:
        description: "Optional python SDK version to verify. Defaults to inputs.providerVersion."
        type: string
        required: false

env:
#{{ .Config.Env | toYaml | indent 2 }}#

jobs:
  verify-release:
    name: verify-release
#{{- if not .Config.ReleaseVerification }}#
    # We don't have any release verification configurations, so we never run this workflow.
    # Configure your .ci-mgmt.yaml files to include the release verification configurations e.g.
    # releaseVerification:
    #   nodejs: path/to/nodejs/project
    #   python: path/to/python/project
    #   dotnet: path/to/dotnet/project
    #   go: path/to/go/project
    if: false
#{{- end }}#
    strategy:
      matrix:
#{{- if .Config.ReleaseVerification }}#
        # We always run on Linux and Windows, and optionally on MacOS. This is because MacOS runners have limited availability.
        # Expression expands to ["ubuntu-latest","windows-latest"] or ["ubuntu-latest","windows-latest","macos-latest"]
        # GitHub expressions don't have 'if' statements, so we use a ternary operator to conditionally include the MacOS runner suffix.
        # See the docs for a similar example to this: https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson
        runner: ${{ fromJSON(format('["ubuntu-latest","windows-latest"{0}]', inputs.enableMacRunner && ',"macos-latest"' || '')) }} #
#{{- else }}#
        # We don't have any release verification configurations, so we only run on Linux to print warnings to help users configure the release verification.
        runner: ["ubuntu-latest"]
#{{- end }}#
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout Repo
        uses: #{{ .Config.ActionVersions.Checkout }}#
        with:
          persist-credentials: false
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: pulumicli, #{{ range $index, $element := .Config.Languages }}##{{if $index}}#, #{{end}}##{{ $element }}##{{end}}#
#{{- if .Config.ReleaseVerification }}#
      #{{- if .Config.AWS }}#
      - name: Configure AWS Credentials
        uses: #{{ .Config.ActionVersions.ConfigureAwsCredentials }}#
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ env.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 7200
          role-session-name: #{{ .Config.Provider }}#@githubActions
          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
      #{{- end }}#
      #{{- if .Config.GCP }}#
      - name: Authenticate to Google Cloud
        uses: #{{ .Config.ActionVersions.GoogleAuth }}#
        with:
          service_account: ${{ env.GOOGLE_CI_SERVICE_ACCOUNT_EMAIL }}
          workload_identity_provider: projects/${{ env.GOOGLE_PROJECT_NUMBER
            }}/locations/global/workloadIdentityPools/${{
            env.GOOGLE_CI_WORKLOAD_IDENTITY_POOL }}/providers/${{
            env.GOOGLE_CI_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Setup gcloud auth
        uses: #{{ .Config.ActionVersions.SetupGcloud }}#
        with:
          install_components: gke-gcloud-auth-plugin
      #{{- end }}#
      #{{- if .Config.GCPRegistry }}#
      - name: Login to Google Cloud Registry
        run: gcloud --quiet auth configure-docker
      #{{- end }}#
#{{- if .Config.Actions.PreTest }}#
#{{ .Config.Actions.PreTest | toYaml | indent 6 }}#
#{{- end }}#
#{{- if .Config.ReleaseVerification.Nodejs }}#
      - name: Verify nodejs release
        uses: pulumi/verify-provider-release@v1
        with:
          runtime: nodejs
          directory: #{{ .Config.ReleaseVerification.Nodejs }}#
          provider: #{{ .Config.Provider }}#
          providerVersion: ${{ inputs.providerVersion }}
#{{- end }}#
#{{- if .Config.ReleaseVerification.Python }}#
      - name: Verify python release
        uses: pulumi/verify-provider-release@v1
        with:
          runtime: python
          directory: #{{ .Config.ReleaseVerification.Python }}#
          provider: #{{ .Config.Provider }}#
          providerVersion: ${{ inputs.providerVersion }}
          packageVersion: ${{ inputs.pythonVersion || inputs.providerVersion }}
#{{- end }}#
#{{- if .Config.ReleaseVerification.Dotnet }}#
      - name: Verify dotnet release
        uses: pulumi/verify-provider-release@v1
        with:
          runtime: dotnet
          directory: #{{ .Config.ReleaseVerification.Dotnet }}#
          provider: #{{ .Config.Provider }}#
          providerVersion: ${{ inputs.providerVersion }}
#{{- end }}#
#{{- if .Config.ReleaseVerification.Go }}#
      - name: Verify go release
        uses: pulumi/verify-provider-release@v1
        if: inputs.skipGoSdk == false
        with:
          runtime: go
          directory: #{{ .Config.ReleaseVerification.Go }}#
          provider: #{{ .Config.Provider }}#
          providerVersion: ${{ inputs.providerVersion }}
#{{- end }}#
#{{- end }}#
