package migrations

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// moving the mise.toml file to the `.config` directory.
// This allows users to override the file by placing a mise file
// at the root of the repo. see https://mise.jdx.dev/configuration.html
type deleteMiseConfig struct{}

func (deleteMiseConfig) Name() string {
	return "Remove old mise.toml file"
}
func (deleteMiseConfig) ShouldRun(templateName string) bool {
	return templateName == "bridged-provider" ||
		templateName == "external-bridged-provider" ||
		templateName == "generic" ||
		templateName == "parameterized-go"
}
func (deleteMiseConfig) Migrate(templateName, outDir string) error {
	oldPath := filepath.Join(outDir, "mise.toml")
	oldFile, err := os.ReadFile(oldPath)
	if err != nil {
		return nil
	}

	if strings.Contains(string(oldFile), "# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/pulumi/ci-mgmt") {
		if err := os.Remove(oldPath); err != nil {
			return fmt.Errorf("could not remove old mise.toml: %w", err)
		}

	}

	return nil
}
