template: external-bridged-provider
provider: acme
organization: pulumiverse
major-version: 0
providerDefaultBranch: main
upstreamProviderOrg: vancluever
publishRegistry: false
languages:
    - dotnet
    - go
    - nodejs
    - python
publish:
    sdk: "all,!java"
    cdn: false
license:
    ignore:
        # Package is licensed under Apache 2.0 but license is not picked up correctly by the license detector
        - github.com/OpenDNS/vegadns2client
        - github.com/alibabacloud-go/endpoint-util
        - github.com/nrdcg/oci-go-sdk
        - github.com/cespare/xxhash
        - github.com/envoyproxy/protoc-gen-validate
        - github.com/go-acme/tencentclouddnspod
        - github.com/go-acme/tencentedgdeone
pulumiConvert: 1
