name: Download binary assets
description: Downloads provider binaries to `bin/`.

runs:
  using: "composite"
  steps:
    - name: Download provider binaries
      uses: #{{ .Config.ActionVersions.DownloadArtifact }}#
      with:
        name: #{{ .Config.Provider }}#-provider.tar.gz
        path: ${{ github.workspace }}/bin
    - name: Untar provider binaries
      shell: bash
      run: |
        tar -zxf ${{ github.workspace }}/bin/provider.tar.gz -C ${{ github.workspace}}/bin
        find ${{ github.workspace }} -name "pulumi-*-#{{ .Config.Provider }}#" -print -exec chmod +x {} \;
