name: nightly-sdk-generation
on:
  schedule:
  - cron: 35 4 * * 1-5
  workflow_dispatch: {}
env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
  PROVIDER: google-native
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NUGET_PUBLISH_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  TRAVIS_OS_NAME: linux
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
  GOOGLE_PROJECT: pulumi-ci-gcp-provider
  GOOGLE_REGION: us-central1
  GOOGLE_ZONE: us-central1-a
  PULUMI_API: https://api.pulumi-staging.io
jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    name: generate-sdk
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.x
    - name: Install pulumictl
      uses: jaxxstorm/action-install-gh-release@v1.5.0
      with:
        repo: pulumi/pulumictl
    - name: Install Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v2
    - name: Cleanup SDK Folder
      run: make clean
    - name: Preparing Git Branch
      run: >
        git config --local user.email "bot@pulumi.com"

        git config --local user.name "pulumi-bot"

        git checkout -b generate-sdk/${{ github.run_id }}-${{ github.run_number }}
    - name: Commit Empty SDK
      run: |-
        git add . 
        git commit -m "Preparing the SDK folder for regeneration"
    - name: Discovery
      id: discovery
      run: |-
        make discovery
        git update-index -q --refresh
    - name: Build codegen binaries
      run: make codegen
    - name: Build Schema + SDKs
      run: make local_generate
    - name: Commit changes
      run: >-
        git add discovery

        git commit -m "Discovery documents"

        git add .

        git commit -m "Regenerating based on discovery"

        git push origin generate-sdk/${{ github.run_id }}-${{ github.run_number }}
    - name: Create PR
      id: create-pr
      uses: repo-sync/pull-request@v2.6.2
      with:
        destination_branch: master
        github_token: ${{ secrets.PULUMI_BOT_TOKEN }}
        pr_body: "*Automated PR*"
        pr_title: Automated SDK generation
        author_name: pulumi-bot
        source_branch: generate-sdk/${{ github.run_id }}-${{ github.run_number }}
    - name: Set AutoMerge
      if: steps.create-pr.outputs.has_changed_files
      uses: peter-evans/enable-pull-request-automerge@v1
      with:
        token: ${{ secrets.PULUMI_BOT_TOKEN }}
        pull-request-number: ${{ steps.create-pr.outputs.pr_number }}
        repository: ${{ github.repository }}
        merge-method: squash
    - if: failure() && github.event_name == 'push'
      name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        author_name: Failure during automated SDK generation
        fields: repo,commit,author,action
        status: ${{ job.status }}
