name: "Build SDK"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
#{{ .Config.env | toYaml | indent 2 }}#
  PROVIDER_VERSION: ${{ inputs.version }}

jobs:
  build_sdk:
    name: build_sdk
    runs-on: #{{ if .Config.runner.buildSdk }}##{{- .Config.runner.buildSdk }}##{{ else }}##{{- .Config.runner.default }}##{{ end }}#
    steps:
      - name: Checkout Repo
        uses: #{{ .Config.actionVersions.checkout }}#
#{{- if .Config.checkoutSubmodules }}#
        with:
          submodules: #{{ .Config.checkoutSubmodules }}#
#{{- end }}#
      - name: Cache examples generation
        uses: actions/cache@v4
        with:
          path: |
            .pulumi/examples-cache
          key: ${{ runner.os }}-${{ hashFiles('provider/go.sum') }}
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: pulumictl, pulumicli, go, node, dotnet, python, java
      - name: Download bin
        uses: ./.github/actions/download-bin
      - name: Install plugins
        run: make install_plugins
      - name: Update path
        run: echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"
      - name: Build SDKs
        run: make -j4 build_sdks
      - name: Check worktree clean
        uses: pulumi/git-status-check-action@v1
        with:
          allowed-changes: |
            sdk/**/pulumi-plugin.json
            sdk/dotnet/Pulumi.*.csproj
            sdk/go/**/pulumiUtilities.go
            sdk/nodejs/package.json
            sdk/python/pyproject.toml
      - name: Tar SDK folder
        run: tar -zcf sdk.tar.gz -C sdk .
      - name: Upload SDK
        uses: actions/upload-artifact@v4
        with:
          name: sdk.tar.gz
          path: ${{ github.workspace}}/sdk.tar.gz
          retention-days: 30
