name: "Build SDK"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
#{{ .Config.Env | toYaml | indent 2 }}#
  PROVIDER_VERSION: ${{ inputs.version }}

jobs:
  build_sdk:
    name: build_sdk
    runs-on: #{{ if .Config.Runner.BuildSDK }}##{{- .Config.Runner.BuildSDK }}##{{ else }}##{{- .Config.Runner.Default }}##{{ end }}#
    strategy:
      fail-fast: true
      matrix:
        language:
#{{ .Config.Languages | toYaml | indent 8 }}#
    steps:
      #{{- if .Config.FreeDiskSpaceBeforeSdkBuild }}#
      # Run as first step so we don't delete things that have just been installed
      - name: Free Disk Space (Ubuntu)
        uses: #{{ .Config.ActionVersions.FreeDiskSpace }}#
        with:
          tool-cache: false
          swap-storage: false
          dotnet: false
      #{{- end }}#
      - name: Checkout Repo
        uses: #{{ .Config.ActionVersions.Checkout }}#
        with:
          #{{- if .Config.CheckoutSubmodules }}#
          submodules: #{{ .Config.CheckoutSubmodules }}#
          #{{- end }}#
          persist-credentials: false
      - name: Cache examples generation
        uses: actions/cache@v4
        with:
          path: |
            .pulumi/examples-cache
          key: ${{ runner.os }}-${{ hashFiles('provider/go.sum') }}
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: pulumictl, pulumicli, ${{ matrix.language }}
      - name: Prepare local workspace
        run: make prepare_local_workspace
      - name: Download bin
        uses: ./.github/actions/download-bin
      - name: Update path
        run: echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"
      - name: Restore makefile progress
        uses: #{{ .Config.ActionVersions.DownloadArtifact }}#
        with:
          name: prerequisites.make
          path: .make
      - name: Build SDK
        run: make build_${{ matrix.language }}
      - name: Check worktree clean
        uses: pulumi/git-status-check-action@v1
        with:
          allowed-changes: |
            sdk/**/pulumi-plugin.json
            sdk/dotnet/*.csproj
            sdk/go/**/pulumiUtilities.go
            sdk/nodejs/package.json
            sdk/python/pyproject.toml
      - name: Upload SDK
        uses: ./.github/actions/upload-sdk
        with:
          language: ${{ matrix.language }}
      - name: Save makefile progress
        uses: #{{ .Config.ActionVersions.UploadArtifact }}#
        with:
          name: build_${{ matrix.language }}.make
          path: .make
          include-hidden-files: true
