name: "Prerequisites"

on:
  workflow_call:

jobs:
  prerequisites:
    name: prerequisites
    runs-on: #{{ .Config.runner.prerequisites }}#
    steps:
    - name: Checkout Repo
      uses: #{{ .Config.actionVersions.checkout }}#
#{{- if .Config.checkoutSubmodules }}#
      with:
        submodules: #{{ .Config.checkoutSubmodules }}#
#{{- end }}#
    - uses: pulumi/provider-version-action@v1
      with:
        set-env: 'PROVIDER_VERSION'
    - name: Cache examples generation
      uses: actions/cache@v4
      with:
        path: |
          .pulumi/examples-cache
        key: ${{ runner.os }}-${{ hashFiles('provider/go.sum') }}
    - name: Prepare upstream code
      run: make upstream
    - name: Install Go
      uses: #{{ .Config.actionVersions.setupGo }}#
      with:
        go-version: "#{{ .Config.toolVersions.go }}#"
        cache-dependency-path: |
          provider/*.sum
          upstream/*.sum
    - name: Install pulumictl
      uses: #{{ .Config.actionVersions.installGhRelease }}#
      with:
        tag: #{{ .Config.actionVersions.pulumictlTag }}#
        repo: pulumi/pulumictl
    - name: Install Pulumi CLI
      uses: #{{ .Config.actionVersions.setupPulumi }}#
      with:
        pulumi-version: "#{{ .Config.toolVersions.pulumi }}#"
    - if: github.event_name == 'pull_request'
      name: Install Schema Tools
      uses: #{{ .Config.actionVersions.installGhRelease }}#
      with:
        repo: pulumi/schema-tools
#{{- if .Config.actions.preBuild }}#
#{{ .Config.actions.preBuild | toYaml | indent 4 }}#
#{{- end }}#
    - name: Build schema generator binary
      run: make tfgen_build_only
    - name: Install plugins
      run: make install_plugins
    - name: Generate schema
      run: make tfgen_no_deps
    - name: Build provider binary
      run: make provider_no_deps
    - name: Unit-test provider code
      run: make test_provider
    - if: github.event_name == 'pull_request'
      name: Check Schema is Valid
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        {
          echo "SCHEMA_CHANGES<<$EOF";
          schema-tools compare -p #{{ .Config.provider }}# -o ${{ github.event.repository.default_branch }} -n --local-path=provider/cmd/pulumi-resource-#{{ .Config.provider }}#/schema.json;
          echo "$EOF";
        } >> "$GITHUB_ENV"
    - if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
      name: Comment on PR with Details of Schema Check
      uses: #{{ .Config.actionVersions.prComment }}#
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        comment_tag: schemaCheck
        message: >+
          ${{ env.SCHEMA_CHANGES }}


          Maintainer note: consult the [runbook](https://github.com/pulumi/platform-providers-team/blob/main/playbooks/tf-provider-updating.md) for dealing with any breaking changes.

#{{- if .Config.enableConfigurationCheck }}#
    - if: github.event_name == 'pull_request'
      name: Check Configuration section
      run: |
        sed -n '/## Configuration/,$p' README.md | sed -n '/## Reference/q;p' >> config_section.txt
        jq -r '.config | select(.variables) | .variables | keys[]' < provider/cmd/pulumi-resource-#{{ .Config.provider }}#/schema.json >> keys.txt
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        {
          echo "MISSING_CONFIG<<$EOF";
          xargs -I {} sh -c "grep -q {} config_section.txt || echo \\\`{}\\\` not found in Configuration section" < keys.txt
          echo "$EOF";
        } >> "$GITHUB_ENV"

    - if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
      name: Check for missing config
      run: |
        if [ ! -z "${{ env.MISSING_CONFIG }}" ]; then
        cat <<EOF
        ${{ env.MISSING_CONFIG }}
        EOF
        echo 'Please add a description for each of these options to `README.md`.'
        echo 'Details about them can be found in either the upstream docs or `schema.json`.'
        exit 1
        fi
#{{- end }}#

    - name: Tar provider binaries
      run: tar -zcf ${{ github.workspace }}/bin/provider.tar.gz -C ${{
        github.workspace }}/bin/ pulumi-resource-#{{ .Config.provider }}#
        pulumi-tfgen-#{{ .Config.provider }}#
    - name: Upload artifacts
      uses: #{{ .Config.actionVersions.uploadArtifact }}#
      with:
        name: #{{ .Config.provider }}#-provider.tar.gz
        path: ${{ github.workspace }}/bin/provider.tar.gz
        retention-days: 30
    - if: failure() && github.event_name == 'push'
      name: Notify Slack
      uses: #{{ .Config.actionVersions.notifySlack }}#
      with:
        author_name: Failure in building provider prerequisites
        fields: repo,commit,author,action
        status: ${{ job.status }}
