provider: databricks
major-version: 1
env:
  DATABRICKS_USERNAME: ${{ secrets.DATABRICKS_USERNAME }}
  DATABRICKS_PASSWORD: ${{ secrets.DATABRICKS_PASSWORD}}
  DATABRICKS_ACCOUNT_ID: ${{ secrets.DATABRICKS_ACCOUNT_ID}}
  DATABRICKS_HOST: https://accounts.cloud.databricks.com
upstream-provider-org: databrickslabs
provider-default-branch: main
makeTemplate: bridged
plugins:
  - name: random 
    version: "4.3.1"
  - name: aws 
    version: "5.1.0"
