name: "Build Provider"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build_provider:
    name: Build ${{ matrix.platform.os }}-${{ matrix.platform.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          - os: windows
            arch: amd64
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: pulumictl, go
      - name: Prepare for build
        shell: bash
        # This installs plugins and prepares upstream
        # We have to run tfgen in order to generate the cmd/pulumi-resource-xyz/schema_embed.json file.
        run: make tfgen
      - name: Build & package provider
        shell: bash
        working-directory: provider
        run: make bin/pulumi-resource-docker-v${{ inputs.version }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}.tar.gz
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pulumi-resource-docker-v${{ inputs.version }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}.tar.gz
          path: bin/pulumi-resource-docker-v${{ inputs.version }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}.tar.gz
          retention-days: 30
