name: "Build Provider"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build_provider:
    name: Build ${{ matrix.platform.os }}-${{ matrix.platform.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          - os: windows
            arch: amd64
    steps:
      # Run as first step so we don't delete things that have just been installed
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          tool-cache: false
          swap-storage: false
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: go
      - name: Prepare for build
        shell: bash
        # This installs plugins and prepares upstream
        # TODO: Can we just run `make upstream` here?
        run: make tfgen
      - name: Go build
        shell: bash
        working-directory: provider
        env:
          GOOS: ${{ matrix.platform.os }}
          GOARCH: ${{ matrix.platform.arch }}
          PROVIDER_PATH: provider/v6
        # YAML `>` will join consecutive lines with a space
        run: >
          go build
          -p 2
          -o ${{ github.workspace }}/bin/${{ matrix.platform.os }}-${{ matrix.platform.arch }}/pulumi-resource-aws
          -ldflags "
            -X github.com/pulumi/pulumi-aws/${{ env.PROVIDER_PATH }}/pkg/version.Version=v${{ inputs.version }}
            -X github.com/hashicorp/terraform-provider-aws/version.ProviderVersion=v${{ inputs.version }}
            "
          ./cmd/pulumi-resource-aws
      - name: Package provider binary
        shell: bash
        working-directory: bin/${{ matrix.platform.os }}-${{ matrix.platform.arch }}
        run: >
          tar --gzip -cf bin/pulumi-resource-aws-v${{ inputs.version }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}.tar.gz
          README.md LICENCE
          -C bin/${{ matrix.platform.os }}-${{ matrix.platform.arch }} pulumi-resource-aws
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pulumi-resource-aws-v${{ inputs.version }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}.tar.gz
          path: bin/pulumi-resource-aws-v${{ inputs.version }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}.tar.gz
          retention-days: 30
