provider: fastly
major-version: 8
env:
  FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY }}
makeTemplate: bridged
plugins:
  - name: aws
    version: "5.0.0"
  - name: tls
    version: "4.0.0"
team: ecosystem
