provider: confluent
major-version: 1
env:
  CONFLUENT_CLOUD_USERNAME: ${{ secrets.CONFLUENT_CLOUD_USERNAME }}
  CONFLUENT_CLOUD_PASSWORD: ${{ secrets.CONFLUENT_CLOUD_PASSWORD }}
upstream-provider-org: Mongey
makeTemplate: bridged
plugins:
  - name: random 
    version: "4.1.1"
