template: native
provider: kubernetes-coredns
major-version: 0
pulumiVersionFile: .pulumi.version
setupKind: true
parallel: 3
envOverride:
  AWS_REGION: us-west-2
  GOLANGCI_LINT_VERSION: v1.61.0
  GOOGLE_CI_SERVICE_ACCOUNT_EMAIL: pulumi-ci@pulumi-k8s-provider.iam.gserviceaccount.com
  GOOGLE_CI_WORKLOAD_IDENTITY_POOL: pulumi-ci
  GOOGLE_CI_WORKLOAD_IDENTITY_PROVIDER: pulumi-ci
  PULUMI_TEST_OWNER: moolumi
  GOOGLE_PROJECT_NUMBER: 637339343727
