provider: oci
major-version: 1
lint: false
parallel: 1
timeout: 90
env:
  TF_VAR_tenancy_ocid: ${{ secrets.TF_VAR_tenancy_ocid }}
  TF_VAR_user_ocid: ${{ secrets.TF_VAR_user_ocid }}
  TF_VAR_private_key: ${{ secrets.TF_VAR_private_key }}
  TF_VAR_region: ${{ secrets.TF_VAR_region }}
upstream-provider-org: pulumi
