provider: slack
major-version: 1
env:
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
lint: true
upstream-provider-org: pulumi
provider-default-branch: main
makeTemplate: bridged
plugins:
  - name: random 
    version: "4.3.1"
