provider: slack
major-version: 1
env:
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
lint: true
providerDefaultBranch: main
makeTemplate: bridged
plugins:
  - name: random 
    version: "4.3.1"
team: ecosystem
javaGenVersion: "v0.9.7"
