provider: archive
major-version: 0
lint: false
providerDefaultBranch: main
makeTemplate: bridged
publishRegistry: false
env:
  ARCHIVE_TOKEN: ${{ secrets.ARCHIVE_TOKEN }}
team: ecosystem
javaGenVersion: "v0.9.5"

