import { BridgedConfig } from "./config";
import { render } from "./make";
import { bridgedProvider } from "./make-bridged-provider";

const header = `# WARNING: this file was generated by ci-mgmt. Do not edit directly!\n\n`;

export function buildMakefile(config: BridgedConfig): string {
  switch (config.makeTemplate) {
    case "bridged":
      return header + render(bridgedProvider(config));
    default:
      throw new Error(`Unknown makefile template: ${config.makeTemplate}`);
  }
}
