name: Download the code generator binary
description: Downloads the code generator binary to `bin/`.

runs:
  using: "composite"
  steps:
    - name: Download the prerequisites bin
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: prerequisites-bin
        path: bin

    - name: Restore executable permissions
      shell: bash
      run: chmod +x $(< bin/executables.txt)

    - name: Remove executables list
      shell: bash
      run: rm bin/executables.txt

    
