name: Upload SDK asset
description: Upload the SDK for a specific language as an asset for the workflow.

runs:
  using: "composite"
  steps:
    - name: Capture executable permissions
      shell: bash
      run: find bin -type f -executable > bin/executables.txt

    - name: Upload prerequisites bin
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: prerequisites-bin
        path: bin/*
        retention-days: 30

    
