provider: terraform
major-version: 5
lint: false
skipTfGen: true
aws: true
env:
  AWS_REGION: us-west-2
  TFE_ORGANIZATION: ${{ secrets.TFE_ORGANIZATION }}
  TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
# pulumi-terraform is not a typical bridged provider, so the upgrade process may not work, but since these values are required to generate the workflows anyway,
upstream-provider-org: hashicorp
upstream-provider-repo: terraform
