provider: aws-native
lint: false
major-version: 0
aws: true
submodules: true
enableChangelog: true
pulumiVersionFile: .pulumi.version
env:
  AWS_REGION: us-west-2
  PULUMI_API: "https://api.pulumi-staging.io"
