name: Download SDK asset
description: Restores the SDK asset for a language.

inputs:
  language:
    required: true
    description: One of nodejs, python, dotnet, go, java

runs:
  using: "composite"
  steps:
    - name: Download ${{ inputs.language }} SDK
      uses: #{{ .Config.ActionVersions.DownloadArtifact }}#
      with:
        name: ${{ inputs.language }}-sdk.tar.gz
        path: ${{ github.workspace}}/sdk/
    - name: Uncompress SDK folder (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: mkdir -p ${{ github.workspace }}/sdk/${{ inputs.language }} && tar -zxf ${{ github.workspace }}/sdk/${{ inputs.language }}.tar.gz -C ${{ github.workspace }}/sdk/${{ inputs.language }}
    - name: Uncompress SDK folder (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path "${{ github.workspace }}/sdk/${{ inputs.language }}" | Out-Null
        tar -zxf "${{ github.workspace }}/sdk/${{ inputs.language }}.tar.gz" -C "${{ github.workspace }}/sdk/${{ inputs.language }}"
