provider: rancher2
major-version: 4
lint: false
setup-script: testing/setup.sh
golangci-timeout: 20m
env:
  RANCHER_INSECURE: "true"
  RANCHER_URL: https://localhost # docker
makeTemplate: bridged
team: ecosystem
