provider: google-native
lint: false
major-version: 0
gcp: true
submodules: true
env:
  GOOGLE_PROJECT: pulumi-ci-gcp-provider
  GOOGLE_REGION: us-central1
  GOOGLE_ZONE: us-central1-a
  PULUMI_API: "https://api.pulumi-staging.io"