provider: f5bigip
major-version: 3
aws: true
env:
  AWS_REGION: us-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SDK_LOAD_CONFIG: true
upstream-provider-repo: terraform-provider-bigip
makeTemplate: bridged
team: ecosystem
