name: Download the provider binary
description: Downloads the provider binary to `bin/`.

runs:
  using: "composite"
  steps:

    - name: Download pulumi-resource-#{{ .Config.Provider }}#
      uses: #{{ .Config.ActionVersions.DownloadArtifact }}#
      with:
        pattern: pulumi-resource-#{{ .Config.Provider }}#-*-linux-amd64.tar.gz
        path: ${{ github.workspace }}/bin
        merge-multiple: true

    - name: Untar pulumi-resource-#{{ .Config.Provider }}#
      shell: bash
      run: |
        tar -zxf ${{ github.workspace }}/bin/*amd64.tar.gz -C ${{ github.workspace}}/bin

    - name: Mark pulumi-resource-#{{ .Config.Provider }}# as executable
      shell: bash
      run: |
        find ${{ github.workspace }} -name "pulumi-*-#{{ .Config.Provider }}#" -print -exec chmod +x {} \;
