provider: tailscale
major-version: 1
env:
  TAILSCALE_API_KEY: ${{ secrets.TAILSCALE_API_KEY }}
  TAILSCALE_TAILNET: ${{ secrets.TAILSCALE_TAILNET }}
makeTemplate: bridged
plugins:
  - name: random 
    version: "4.3.1"
team: ecosystem
