# WARNING: this file is only used as an example to test changes to workflow templates, specifically
# by the test-workflow-generation Makefile target. It does NOT affect the configuration of the
# actual provider. Edit .ci-mgmt.yml in pulumi/pulumi-cloudflare to reconfigure the actual provider
# build.
provider: cloudflare
major-version: 5
makeTemplate: bridged
plugins:
  - name: gcp
    version: "5.0.0"
  - name: tls
    version: "4.0.0"
env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
javaGenVersion: "v0.9.3"
license:
  ignore:
    - github.com/oracle/terraform-provider-oci/shim
