# Generates a PR for the files in provider-ci/providers/* to the corresponding
# Pulumi provider. Note that this workflow does not generate any files -
# workflows must already be generated and committed to this repo when this
# workflow is run.
name: Deploy workflow files to a single provider providers
"on":
  workflow_dispatch:
    inputs:
      provider_name:
        description: The name of the provider to deploy - do not include the pulumi prefix in the name.
        required: true
        type: string
env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone ci-mgmt
        uses: actions/checkout@v2
        with:
          path: ci-mgmt
      - name: Clone pulumi-${{ github.event.inputs.provider_name }}
        uses: actions/checkout@v2
        with:
          repository: pulumi/pulumi-${{ github.event.inputs.provider_name }}
          path: pulumi-${{ github.event.inputs.provider_name }}
      - name: Copy files from ci-mgmt to pulumi-${{ github.event.inputs.provider_name }}
        run: |
          cp -r ci-mgmt/provider-ci/providers/${{ github.event.inputs.provider_name }}/repo/. pulumi-${{ github.event.inputs.provider_name }}/.
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          author: Pulumi Bot <bot@pulumi.com>
          body: "This PR was automatically generated by the deploy-single-provider workflow in the pulumi/ci-mgmt repo."
          branch: "update-github-actions-workflows-${{ github.run_number }}"
          committer: Pulumi Bot <bot@pulumi.com>
          commit-message: "[internal] Update GitHub Actions workflow files"
          labels: "impact/no-changelog-required, automation/merge"
          title: "Update GitHub Actions workflows."
          team-reviewers: "platform-integrations"
          path: pulumi-${{ github.event.inputs.provider_name }}
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
