# Generates a PR for the files in native-provider-ci/providers/* to each corresponding Pulumi provider.
#
# Note that this workflow does not generate any files - workflows must already be generated and committed to this repo
# when this workflow is run.
name: Update GH workflows, native providers (auto-pr)
on:
  schedule:
  # 5 AM UTC ~ 10 PM PDT - specifically selected to avoid putting load on the CI system during working hours.
  - cron: 0 5 * * *
jobs:
  generate-providers-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-providers
        run: echo "::set-output name=providers::$(python generate_native_providers_list.py --for-auto-pr)'"
        working-directory: scripts
    outputs:
      providers: ${{ steps.get-providers.outputs.providers }}
  update-provider:
    needs: generate-providers-list
    strategy:
      fail-fast: false
      # GitHub recommends only issuing 1 API request per second, and never
      # concurrently.  For more information, see:
      # https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits
      max-parallel: 1
      matrix:
        provider: ${{ fromJson(needs.generate-providers-list.outputs.providers ) }}
    uses: ./.github/workflows/update-single-native-provider.yaml
    with:
      provider_name: ${{ matrix.provider }}
    secrets: inherit

