# Performs a workflow_dispatch to run the update-bridge workflow in all
# providers.
name: Run update-bridge for all providers
on:
  workflow_dispatch:
    inputs:
      bridge_version:
        description:
          The version of pulumi/pulumi-terraform-bridge to update to. Do
          not include the 'v' prefix. Must be major version 3.
        required: true
        type: string
      sdk_version:
        description:
          The version of pulumi/pulumi/sdk to update to. Do not include
          the 'v' prefix. Must be major version 3.
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
jobs:
  generate-providers-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-providers
        run: echo "::set-output name=providers::$(python generate_providers_list.py)'"
        working-directory: scripts
    outputs:
      providers: ${{ steps.get-providers.outputs.providers }}

  update-bridge:
    needs: generate-providers-list
    runs-on: ubuntu-latest
    strategy:
      # GitHub recommends only issuing 1 API request per second, and never
      # concurrently.  For more information, see:
      # https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits
      max-parallel: 1
      matrix:
        provider: ${{ fromJson(needs.generate-providers-list.outputs.providers ) }}
    steps:
      - name: pulumi-${{ matrix.provider }}
        run: gh workflow run update-bridge.yml -f bridge_version=${{ github.event.inputs.brdige_version }} -f sdk_version=${{ github.event.inputs.sdk_version }}
      # See: https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits
      - name: Sleep to prevent hitting secondary rate limits
        run: sleep 1
