name: Update All Providers
on:
  - workflow_dispatch
jobs:
  generate-providers-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-providers
        run: echo "::set-output name=providers::$(python generate_providers_list.py)'"
        working-directory: scripts
    outputs:
      providers: ${{ steps.get-providers.outputs.providers }}

  update_all:
    needs: generate-providers-list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: ${{ fromJson(needs.generate-providers-list.outputs.providers ) }}
    steps:
      - run: echo "${{ matrix.provider }}"
