# Generates a PR for the files in provider-ci/providers/* to the corresponding
# Pulumi provider. Note that this workflow does not generate any files -
# workflows must already be generated and committed to this repo when this
# workflow is run.
name: Update GH workflow files, all providers
on:
  - workflow_dispatch
env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
jobs:
  generate-providers-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-providers
        run: echo "::set-output name=providers::$(python generate_providers_list.py)'"
        working-directory: scripts
    outputs:
      providers: ${{ steps.get-providers.outputs.providers }}

  deploy:
    needs: generate-providers-list
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # GitHub recommends only issuing 1 API request per second, and never
      # concurrently.  For more information, see:
      # https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits
      max-parallel: 1
      matrix:
        provider: ${{ fromJson(needs.generate-providers-list.outputs.providers ) }}
    steps:
      - name: Clone ci-mgmt
        uses: actions/checkout@v2
        with:
          path: ci-mgmt
      - name: Clone pulumi-${{ matrix.provider }}
        uses: actions/checkout@v2
        with:
          repository: pulumi/pulumi-${{ matrix.provider }}
          path: pulumi-${{ matrix.provider }}
      - name: Delete existing workflows
        run: rm pulumi-${{ matrix.provider }}/.github/workflows/*.yml
      - name: Copy files from ci-mgmt to pulumi-${{ matrix.provider }}
        run: |
          cp -r ci-mgmt/provider-ci/providers/${{ matrix.provider }}/repo/. pulumi-${{ matrix.provider }}/.
      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          author: Pulumi Bot <bot@pulumi.com>
          body: "This PR was automatically generated by the update-all-providers workflow in the pulumi/ci-mgmt repo."
          branch: "update-github-actions-workflows-${{ github.run_number }}"
          committer: Pulumi Bot <bot@pulumi.com>
          commit-message: "[internal] Update GitHub Actions workflow files"
          labels: "impact/no-changelog-required"
          title: "Update GitHub Actions workflows."
          path: pulumi-${{ matrix.provider }}
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
      - name: Set PR to auto-merge
        if: steps.create-pr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          repository: pulumi/pulumi-${{ matrix.provider }}
          merge-method: squash
        # See: https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits
      - name: Sleep to prevent hitting secondary rate limits
        run: sleep 1
