# Update pulumi/pulumi-java used in all providers to a target version.
name: update-java

permissions: write-all # Equivalent to default permissions plus id-token: write

on:
  workflow_dispatch:
    inputs:
      pulumi-java-version:
        description: Desired version of pulumi/pulumi-java to ugprade to.
        required: true
        type: string
      provider:
        description: |
          A single provider, such as 'aws', to update. If 'all' all providers are updated.
        required: false
        default: all

env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: github-secrets/pulumi-ci-mgmt
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: GITHUB_TOKEN=PULUMI_BOT_TOKEN

jobs:

  generate-providers-list:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@cf5b30703ffd5ad60cc3a880c09b3a9592b9372d # v1
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - id: get-providers
        shell: bash
        env:
          PROVIDER: ${{inputs.provider}}
        run: |
            case "$PROVIDER" in
                all)
                    echo "providers=$(jq . providers.json --compact-output)" >> "$GITHUB_OUTPUT"
                    ;;

                *)
                    echo "providers=[\"${PROVIDER}\"]" >> "$GITHUB_OUTPUT"
                    ;;
            esac
        working-directory: provider-ci
    outputs:
      providers: ${{ steps.get-providers.outputs.providers }}

  update-java:
    needs: generate-providers-list
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # GitHub recommends only issuing 1 API request per second, and never
      # concurrently.  For more information, see:
      # https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits
      max-parallel: 1
      matrix:
        provider: ${{ fromJson(needs.generate-providers-list.outputs.providers ) }}

    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@cf5b30703ffd5ad60cc3a880c09b3a9592b9372d # v1
      - name: Format inputs
        shell: bash
        id: format-inputs
        env:
          V: ${{ inputs.pulumi-java-version }}
        run: |
          INPUTS_JSON=$(jq -c -n --arg v "$V" '{version: $v}')
          echo "json=$INPUTS_JSON" >> "$GITHUB_OUTPUT"
      - name: pulumi-${{ matrix.provider }} main
        id: upgrade-on-main
        uses: benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc # v1.2.4
        continue-on-error: true
        with:
            workflow: upgrade-java.yml
            token: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}
            repo: pulumi/pulumi-${{ matrix.provider }}
            inputs: ${{ steps.format-inputs.outputs.json }}
            ref: main
      - name: pulumi-${{ matrix.provider }} master
        id: upgrade-on-master
        if: steps.upgrade-on-main.outcome == 'failure'
        uses: benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc # v1.2.4
        with:
            workflow: upgrade-java.yml
            token: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}
            repo: pulumi/pulumi-${{ matrix.provider }}
            ref: master
            inputs: ${{ steps.format-inputs.outputs.json }}
      - name: Sleep to prevent hitting secondary rate limits
        run: sleep 1
