# WARNING: This file is autogenerated - changes will be overwritten if not made
# via https://github.com/pulumi/ci-mgmt.
#
# This file contains default variables consumed by CI workflows.
#
PACK := #{{ .Config.Provider }}#
ORG := #{{ .Config.Organization }}#
PROJECT := github.com/$(ORG)/pulumi-$(PACK)
#{{- if ge .Config.MajorVersion 2 }}#
PROVIDER_PATH := provider/v#{{ .Config.MajorVersion }}#
#{{- else }}#
PROVIDER_PATH := provider
#{{- end }}#
VERSION_PATH := $(PROVIDER_PATH)/pkg/version.Version
SCHEMA_PATH := provider/cmd/$(PROVIDER)/schema.json
PROVIDER := pulumi-resource-$(PACK)
JAVA_GEN := pulumi-java-gen
JAVA_GEN_VERSION := v0.16.1
TESTPARALLELISM := 10
WORKING_DIR := $(shell pwd)
#{{- if .Config.GoBuildParallelism }}#
PULUMI_PROVIDER_BUILD_PARALLELISM ?= -p #{{ .Config.GoBuildParallelism }}#
#{{- else }}#
PULUMI_PROVIDER_BUILD_PARALLELISM ?=
#{{- end }}#
#{{- if .Config.PulumiConvert }}#
PULUMI_CONVERT := 1
#{{- else }}#
PULUMI_CONVERT := 0
#{{- end }}#
PULUMI_MISSING_DOCS_ERROR := true

# Override during CI using `make [TARGET] PROVIDER_VERSION=""` or by setting a PROVIDER_VERSION environment variable
# Local & branch builds will just used this fixed default version unless specified
PROVIDER_VERSION ?= #{{ .Config.MajorVersion }}#.0.0-alpha.0+dev
# Use this normalised version everywhere rather than the raw input to ensure consistency.
VERSION_GENERIC = $(shell pulumictl convert-version --language generic --version "$(PROVIDER_VERSION)")

LDFLAGS_PROJ_VERSION=-X $(PROJECT)/$(VERSION_PATH)=$(VERSION_GENERIC)#{{if .Config.ProviderVersion}}# -X #{{ .Config.ProviderVersion }}#=$(VERSION_GENERIC)#{{end}}#
#{{- if .Config.ProviderVersion }}#
LDFLAGS_UPSTREAM_VERSION=-X #{{ .Config.ProviderVersion }}#=v$(VERSION_GENERIC)
#{{- else }}#
LDFLAGS_UPSTREAM_VERSION=
#{{- end }}#
LDFLAGS_EXTRAS=#{{- range .Config.ExtraLDFlags }}# #{{ . }}# #{{- end }}#
LDFLAGS=$(LDFLAGS_PROJ_VERSION) $(LDFLAGS_UPSTREAM_VERSION) $(LDFLAGS_EXTRAS)

