provider: auth0
preferredSchemaChecker: pulumi/schema-tools
env:
  AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
  AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
upstream-provider-org: auth0
makeTemplate: bridged
